package ch.uzh.ifi.seal.soprafs19.constant;

public enum GodCard {
    APOLLO, ARTEMIS, ATHENA, ATLAS, DEMETER, HEPHESTUS, HERMES, MINOTAUR, PAN, PROMETHEUS,
    APHRODITE, ARES, BIQ, CHAOS, CHARON, CHRONUS, CIRCE, DIONYSUS, EROS, HERA,
    HESTIA, HYPNUS, LIMUS, MEDUSA, MORPHEUS, PERSEPHONE, POSEIDON, SELENE, TRITON, ZEUS
}
